version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: vallit
      POSTGRES_PASSWORD: vallit
      POSTGRES_DB: vallit
    ports: [ "5432:5432" ]
    volumes: [ "pg:/var/lib/postgresql/data" ]

  redis:
    image: redis:7
    ports: [ "6379:6379" ]

volumes:
  pg: {}
